### ISSUE TITLE
TwentyTwenty JS Support

### ISSUE THREAD

**Issue by CatOnly** [obgnail/typora_plugin#842]
Please support it:
https://zurb.com/playground/twentytwenty

by the way, GOOD JOB !

**Comment by obgnail** [comment]
@CatOnly 

Thanks for your feedback!

How would you like to introduce TwentyTwentyJS into typora_plugin? As a code block language, or something else?

**Comment by CatOnly** [comment]
Make it as a button to create a template html code to quick insert it. So we can easily insert it into the table.

**Comment by CatOnly** [comment]
Try label iframe, it can be used in typroa (Windows only, Mac OS block the iframe's JS for Cross-domain)

**Comment by obgnail** [comment]
I am not a front-end programmer. I'm unsure how to Implement this requirement using the <iframe> element. Could you provide an example?

- The <iframe>'s src attribute should reference a separate HTML file, rather than containing embedded HTML code directly. This makes it dependent on an external resource.
- Due to Typora's security policy, iframes will not be able to access local images, which greatly reduces the usefulness of this feature when using pure HTML.

reference：[typora.io - Embed Video, Media or Web Contents](https://support.typora.io/Media/)

**Comment by obgnail** [comment]
I'm closing this issue for now due to inactivity. If you have any new ideas or updates, feel free to drop a comment below.
